version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: textlint
    versions:
    - 11.8.2
    - 11.8.3
