name: Deploy

on:
  push:
    branches:
    - master

jobs:
  generate-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Slack Comment
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ${{github.sha}}${{' のデプロイを開始するよ。'}}
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run generate
      env:
        CI: true
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: ${{ failure() }}
      with:
        type: ${{ job.status }}
        job_name: '*Generate Test*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#blog'
        url: ${{ secrets.SLACK_WEBHOOK }}

  lint-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run lint
      env:
        CI: true
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: ${{ failure() }}
      with:
        type: ${{ job.status }}
        job_name: '*Lint Test*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#blog'
        url: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    needs: [generate-test, lint-test]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: generate
      run: |
        npm i
        npm run generate
      env:
        CI: true
    - name: deploy
      run: |
        npm i
        npm run deploy
      env:
        CI: true
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_HOST: ${{ secrets.FTP_HOST }}
    - name: Slack Comment
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: 'デプロイしたよ。お疲れ、skawashima。'
