name: Node CI

on:
  push:
    branches-ignore:
    - master

jobs:
  generate-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run generate
      env:
        CI: true
    - name: Slack Comment
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_OVERRIDE_MESSAGE: 'Generate Test が終わったよ。' # Optional.
      with:
        args: 'Generate test.'
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Generate Test*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#cocktail-menu'
        url: ${{ secrets.SLACK_WEBHOOK }}

  lint-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run lint
      env:
        CI: true
    - name: Slack Comment
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_OVERRIDE_MESSAGE: 'Lint Test が終わったよ' # Optional.
      with:
        args: 'Lint test.'
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Lint Test*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#cocktail-menu'
        url: ${{ secrets.SLACK_WEBHOOK }}
